version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - TAKE_FILE_OWNERSHIP=1
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    ports:
      - 5601:5601
